# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57654f1fb909636bb98cfcc70b98ccda2a5cc5eb0851ffc0a6bfaada4d1acdbf5e0b52122fec4f3fd810016f26096391d24145f183856e2f12971231da8c8998

test:
  secret_key_base: 973755f16c9664ad50f16f6e051c574c07a1d44b61f19c40949105f34e60e14084589a038d52182796b63a3c385afac71977cc510fcbd2453810339b78b73c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
